In [3]:
import pandas as pd

In [4]:
path=r"C:\Users\chait\OneDrive\Documents\Generative-Ai\Generative-AI\Gen-AI\IMDB Dataset.csv"
df=pd.read_csv(path)

In [5]:
df.head(100)

                                               review sentiment
0   One of the other reviewers has mentioned that ...  positive
1   A wonderful little production. <br /><br />The...  positive
2   I thought this was a wonderful way to spend ti...  positive
3   Basically there's a family where a little boy ...  negative
4   Petter Mattei's "Love in the Time of Money" is...  positive
..                                                ...       ...
95  Daniel Day-Lewis is the most versatile actor a...  positive
96  My guess would be this was originally going to...  negative
97  Well, I like to watch bad horror B-Movies, cau...  negative
98  This IS the worst movie I have ever seen, as w...  negative
99  I have been a Mario fan for as long as I can r...  positive

[100 rows x 2 columns]

In [6]:
df.shape

(50000, 2)

In [7]:
df=df.head(100)

In [8]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [9]:
df['review']=df['review'].str.lower()

df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [10]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [11]:
#removal of html tags
import re
def remove_html_tags(text):
    clean=re.compile('<.*?>')
    return re.sub(clean,'',text)

In [12]:
text="<p>This is a <b>sample</b> text after removing <a href='#'>HTML tags</a>.</p>"
cleaned_text = remove_html_tags(text)
cleaned_text

'This is a sample text after removing HTML tags.'

In [13]:
df['review']=df['review'].apply(remove_html_tags)

In [14]:
def remove_url(text):
    pattern=re.compile(r'https?://\S+|www\.\S+')
    return re.sub(pattern,'',text)

In [15]:
text="this is my linked in profile https://www.linkedin.com/in/chaitanyasai07/"
cleaned_text = remove_url(text)
cleaned_text

'this is my linked in profile '

In [16]:
#removed urls from the reviews
df['review'] = df['review'].apply(remove_url)

In [17]:
import string,time
exclude=string.punctuation

In [18]:
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', exclude))

In [19]:
text="this, is , a sample. text with removed! punctuation"
start=time.time()
cleaned_text = remove_punctuation(text)
end=time.time()-start
print(f"Time taken to remove punctuation: {end*50000} seconds")
cleaned_text

Time taken to remove punctuation: 0.0 seconds

'this is  a sample text with removed punctuation'

In [20]:
df['review']=df['review'].apply(remove_punctuation)
df['review'][8]

'encouraged by the positive comments about this film on here i was looking forward to watching this film bad mistake ive seen 950 films and this is truly one of the worst of them  its awful in almost every way editing pacing storyline acting soundtrack the films only song  a lame country tune  is played no less than four times the film looks cheap and nasty and is boring in the extreme rarely have i been so happy to see the end credits of a film the only thing that prevents me giving this a 1score is harvey keitel  while this is far from his best performance he at least seems to be making a bit of an effort one for keitel obsessives only'

In [21]:
chat_words={
    "u": "you",
    "r": "are",
    "4": "for", 
    "ur": "your",
    "afk": "away from keyboard",
    "brb": "be right back",
    "btw": "by the way",
    "imo": "in my opinion",
    "idk": "I don't know",
    "lmao": "laughing my ass off",
    "afaik":"as far as i know",
    "ikr":"i know right",
    "faq":"frequently asked question",
    "fyi":"for your information"
}

In [22]:
def chat_convertion(text):
    new_text=[]
    for w in text.split():
        if(w.lower() in chat_words):
            new_text.append(chat_words[w.lower()])
        else:
            new_text.append(w)

    return " ".join(new_text)

In [23]:
chat_convertion('btw , u r going to do this 4 ur project')

'by the way , you are going to do this for your project'

In [25]:
from textblob import TextBlob

In [26]:
#to correct spelling mistakes
from textblob import TextBlob

incorrect_text = "the spallings of thuis santance is changus after usjng textbolbb"
blob = TextBlob(incorrect_text)

# Option 1: just print the corrected TextBlob
print(blob.correct())

# Option 2: get a plain string
corrected = str(blob.correct())

the swellings of this sentence is changes after using textbolbb

In [27]:
#stopwords removal
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\chait\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [28]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [29]:
len(stopwords.words('english'))

198

In [30]:
def remove_stopwords(text):
    newtext=[]
    for word in text.split():
        if word in stopwords.words('english'):
            newtext.append('')
        else:
            newtext.append(word)
    x=newtext[:]
    newtext.clear()
    return " ".join(x)

In [31]:
remove_stopwords('this is a sample text with some stopwords like the and is')

'   sample text   stopwords like   '

In [32]:
df['review']=df['review'].apply(remove_stopwords)

In [33]:
df.head(20)

                                               review sentiment
0   one    reviewers  mentioned   watching  1 oz e...  positive
1    wonderful little production  filming techniqu...  positive
2    thought    wonderful way  spend time    hot s...  positive
3   basically theres  family   little boy jake thi...  negative
4   petter matteis love   time  money   visually s...  positive
5   probably  alltime favorite movie  story  selfl...  positive
6    sure would like  see  resurrection    dated s...  positive
7    show   amazing fresh innovative idea   70s   ...  negative
8   encouraged   positive comments   film     look...  negative
9     like original gut wrenching laughter   like ...  positive
10  phil  alien  one   quirky films   humour  base...  negative
11   saw  movie     12   came   recall  scariest s...  negative
12   im   big fan  bolls work     many   enjoyed  ...  negative
13   cast played shakespeareshakespeare losti appr...  negative
14    fantastic movie  three prisoners  become fam...  positive
15  kind  drawn    erotic scenes   realize   one  ...  negative
16   films  simply    remade   one           bad f...  positive
17   movie made   one   top 10  awful movies horri...  negative
18   remember  filmit   first film   watched   cin...  positive
19   awful film  must      real stinkers   nominat...  negative

In [34]:
#emojis removal
def remove_emojis(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"  # symbols & pictographs
        "\U0001F680-\U0001F6FF"  # transport & map symbols
        "\U0001F1E0-\U0001F1FF"  # flags (iOS)
        "\U00002702-\U000027B0"  # dingbats
        "\U000024C2-\U0001F251"  # enclosed characters
        "]+",
        flags=re.UNICODE,
    )
    return emoji_pattern.sub(r'', text)

In [35]:
remove_emojis('This is a sample text with emojis 😊🚀 and some more text.')

'This is a sample text with emojis  and some more text.'

In [36]:
remove_emojis("lol 😂😂😂")

'lol '

In [37]:
df['review']=df['review'].apply(remove_emojis)

In [40]:
import emoji
print(emoji.demojize('😂'))
emoji.demojize('the movie of 🔥')

:face_with_tears_of_joy:

'the movie of :fire:'

In [41]:
#tokenization
from nltk.tokenize import word_tokenize, sent_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\chait\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [42]:
sent="hello, how are you?"
tokens=word_tokenize(sent)
print(tokens)

['hello', ',', 'how', 'are', 'you', '?']

In [43]:
import nltk
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
wordnet_lemmatizer = WordNetLemmatizer()

sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."
punctuations="?:!.,;"
sentence_words = nltk.word_tokenize(sentence)
for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

sentence_words
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
    print ("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word,pos='v')))

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\chait\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\chait\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

Word                Lemma
He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun

In [44]:
#Feature Extraction
df=pd.DataFrame({'text':["I am running","He was running","They are playing","She is swimming"],'output':[0,1,0,1]})

In [45]:
df

               text  output
0      I am running       0
1    He was running       1
2  They are playing       0
3   She is swimming       1

In [46]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [47]:
bow=cv.fit_transform(df['text'])

In [48]:
print(cv.vocabulary_)

{'am': 0, 'running': 5, 'he': 2, 'was': 9, 'they': 8, 'are': 1, 'playing': 4, 'she': 6, 'is': 3, 'swimming': 7}

In [49]:
bow.toarray()

array([[1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 1, 0, 0]], dtype=int64)

In [50]:
print(bow[0].toarray())

[[1 0 0 0 0 1 0 0 0 0]]

In [51]:
cv.transform(['she is running']).toarray()

array([[0, 0, 0, 1, 0, 1, 1, 0, 0, 0]], dtype=int64)

In [52]:
X=bow.toarray()
y=df['output']

In [53]:
#N-grams
cv=CountVectorizer(ngram_range=(2,2))

In [54]:
bow=cv.fit_transform(df['text'])

In [55]:
print(cv.vocabulary_)

{'am running': 0, 'he was': 2, 'was running': 6, 'they are': 5, 'are playing': 1, 'she is': 4, 'is swimming': 3}

In [56]:
bow[0].toarray()

array([[1, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [57]:
cv.transform(['they are swimming']).toarray()

array([[0, 0, 0, 0, 0, 1, 0]], dtype=int64)

In [58]:
#above we considered two-grams(words) so it is called are bigrams same way we can form trigrams, four-grams etc.

In [59]:
#TF-IDF term frequency-inverse document frequency
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()

In [60]:
arr=tfidf.fit_transform(df['text'])

In [61]:
arr.toarray()

array([[0.78528828, 0.        , 0.        , 0.        , 0.        ,
        0.6191303 , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.61761437, 0.        , 0.        ,
        0.48693426, 0.        , 0.        , 0.        , 0.61761437],
       [0.        , 0.57735027, 0.        , 0.        , 0.57735027,
        0.        , 0.        , 0.        , 0.57735027, 0.        ],
       [0.        , 0.        , 0.        , 0.57735027, 0.        ,
        0.        , 0.57735027, 0.57735027, 0.        , 0.        ]])

In [62]:
print(arr.toarray())

[[0.78528828 0.         0.         0.         0.         0.6191303
  0.         0.         0.         0.        ]
 [0.         0.         0.61761437 0.         0.         0.48693426
  0.         0.         0.         0.61761437]
 [0.         0.57735027 0.         0.         0.57735027 0.
  0.         0.         0.57735027 0.        ]
 [0.         0.         0.         0.57735027 0.         0.
  0.57735027 0.57735027 0.         0.        ]]

In [63]:
import gensim
import os
import pandas as pd
import numpy as np

In [64]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\chait\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [65]:
data=r"C:\Users\chait\OneDrive\Documents\Generative-Ai\Generative-AI\Gen-AI\gameofthrones.txt"

In [66]:
story = []

# Read the file
with open(data, "r", encoding="utf-8") as f:
    corpus = f.read()

# Sentence tokenization
raw_sentences = sent_tokenize(corpus)

# Preprocess each sentence
for sent in raw_sentences:
    story.append(simple_preprocess(sent))

In [67]:
story

[['storm',
  'of',
  'swords',
  'book',
  'three',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george'],
 ['martin',
  'note',
  'on',
  'chronology',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'is',
  'told',
  'through',
  'the',
  'eyes',
  'of',
  'characters',
  'who',
  'are',
  'sometimes',
  'hundreds',
  'or',
  'even',
  'thousands',
  'of',
  'miles',
  'apart',
  'from',
  'one',
  'another'],
 ['some',
  'chapters',
  'cover',
  'day',
  'some',
  'only',
  'an',
  'hour',
  'others',
  'might',
  'span',
  'fortnight',
  'month',
  'half',
  'year'],
 ['with',
  'such',
  'structure',
  'the',
  'narrative',
  'cannot',
  'be',
  'strictly',
  'sequential',
  'sometimes',
  'important',
  'things',
  'are',
  'happening',
  'simultaneously',
  'thousand',
  'leagues',
  'apart'],
 ['in',
  'the',
  'case',
  'of',
  'the',
  'volume',
  'now',
  'in',
  'hand',
  'the',
  'reader',
  'should',
  'realize',
  'that',
  'the',
  'opening',
  'chapters',
  'of',
  'storm',
  'of',
  'swords',
  'do',
  'not',
  'follow',
  'the',
  'closing',
  'chapters',
  'of',
  'clash',
  'of',
  'kings',
  'so',
  'much',
  'as',
  'overlap',
  'them'],
 ['open',
  'with',
  'look',
  'at',
  'some',
  'of',
  'the',
  'things',
  'that',
  'were',
  'happening',
  'on',
  'the',
  'fist',
  'of',
  'the',
  'first',
  'men',
  'at',
  'riverrun',
  'harrenhal',
  'and',
  'on',
  'the',
  'trident',
  'while',
  'thebattleof',
  'the',
  'blackwater',
  'was',
  'being',
  'fought',
  'at',
  'king',
  'landing',
  'and',
  'during',
  'its',
  'aftermath',
  'george',
  'martin',
  'prologue',
  'the',
  'day',
  'was',
  'grey',
  'and',
  'bitter',
  'cold',
  'and',
  'the',
  'dogs',
  'would',
  'not',
  'take',
  'the',
  'scent'],
 ['the',
  'big',
  'black',
  'bitch',
  'had',
  'taken',
  'one',
  'sniff',
  'at',
  'the',
  'bear',
  'tracks',
  'backed',
  'off',
  'and',
  'skulked',
  'back',
  'to',
  'the',
  'pack',
  'page',
  'with',
  'her',
  'tail',
  'between',
  'her',
  'legs'],
 ['the',
  'dogs',
  'huddled',
  'together',
  'miserably',
  'on',
  'the',
  'riverbank',
  'as',
  'the',
  'wind',
  'snapped',
  'at',
  'them'],
 ['chett',
  'felt',
  'it',
  'too',
  'biting',
  'through',
  'his',
  'layers',
  'of',
  'black',
  'wool',
  'and',
  'boiled',
  'leather'],
 ['it',
  'was',
  'too',
  'bloody',
  'cold',
  'for',
  'man',
  'or',
  'beast',
  'but',
  'here',
  'they',
  'were'],
 ['his',
  'mouth',
  'twisted',
  'and',
  'he',
  'could',
  'almost',
  'feel',
  'the',
  'boils',
  'that',
  'covered',
  'his',
  'cheeks',
  'and',
  'neck',
  'growing',
  'red',
  'and',
  'angry'],
 ['should',
  'be',
  'safe',
  'back',
  'at',
  'the',
  'wall',
  'tending',
  'the',
  'bloodyravens',
  'and',
  'making',
  'fires',
  'for',
  'old',
  'maesteraemon'],
 ['it',
  'was',
  'the',
  'bastard',
  'jon',
  'snow',
  'who',
  'had',
  'taken',
  'that',
  'from',
  'him',
  'him',
  'and',
  'his',
  'fat',
  'friend',
  'sam',
  'tarly'],
 ['it',
  'was',
  'their',
  'fault',
  'he',
  'was',
  'here',
  'freezing',
  'his',
  'bloody',
  'balls',
  'off',
  'with',
  'pack',
  'of',
  'hounds',
  'deep',
  'in',
  'the',
  'haunted',
  'forest'],
 ['seven', 'hells'],
 ['he',
  'gave',
  'the',
  'leashes',
  'hard',
  'yank',
  'to',
  'get',
  'the',
  'dogs',
  'attention'],
 ['track', 'you', 'bastards'],
 ['that', 'bear', 'print'],
 ['you', 'want', 'some', 'meat', 'or', 'no'],
 ['find'],
 ['but', 'the', 'hounds', 'only', 'huddled', 'closer', 'whining'],
 ['chett',
  'snapped',
  'his',
  'short',
  'lash',
  'above',
  'their',
  'heads',
  'and',
  'the',
  'black',
  'bitch',
  'snarled',
  'at',
  'him'],
 ['dog',
  'meat',
  'would',
  'taste',
  'as',
  'good',
  'as',
  'bear',
  'he',
  'warned',
  'her',
  'his',
  'breath',
  'frosting',
  'with',
  'every',
  'word'],
 ['lark',
  'the',
  'sisterman',
  'stood',
  'with',
  'his',
  'arms',
  'crossed',
  'over',
  'his',
  'chest',
  'and',
  'his',
  'hands',
  'tucked',
  'up',
  'into',
  'his',
  'armpits'],
 ['he',
  'wore',
  'black',
  'wool',
  'gloves',
  'but',
  'he',
  'was',
  'always',
  'complaining',
  'how',
  'his',
  'fingers',
  'were',
  'frozen'],
 ['it', 'too', 'bloody', 'cold', 'to', 'hunt', 'he', 'said'],
 ['bugger', 'this', 'bear', 'he', 'not', 'worth', 'freezing', 'over'],
 ['we',
  'can',
  'go',
  'back',
  'emptyhand',
  'lark',
  'rumbled',
  'small',
  'paul',
  'through',
  'the',
  'brown',
  'whiskers',
  'that',
  'covered',
  'most',
  'of',
  'his',
  'face'],
 ['the', 'lord', 'commander', 'wouldn', 'like', 'that'],
 ['there',
  'was',
  'ice',
  'under',
  'the',
  'big',
  'man',
  'squashed',
  'pug',
  'nose',
  'where',
  'his',
  'snot',
  'had',
  'frozen'],
 ['huge',
  'hand',
  'in',
  'thick',
  'fur',
  'glove',
  'clenched',
  'tight',
  'around',
  'the',
  'shaft',
  'of',
  'spear'],
 ['bugger',
  'that',
  'old',
  'bear',
  'too',
  'said',
  'the',
  'sisterman',
  'thin',
  'man',
  'with',
  'sharp',
  'features',
  'and',
  'nervous',
  'eyes'],
 ['mormont', 'will', 'be', 'dead', 'before', 'daybreak', 'remember'],
 ['who', 'cares', 'what', 'he', 'likes'],
 ['small', 'paul', 'blinked', 'his', 'black', 'little', 'eyes'],
 ['maybe',
  'he',
  'had',
  'forgotten',
  'chett',
  'thought',
  'he',
  'was',
  'stupid',
  'enough',
  'to',
  'forget',
  'most',
  'anything'],
 ['why', 'do', 'we', 'have', 'to', 'kill', 'the', 'old', 'bear'],
 ['why', 'don', 'we', 'just', 'go', 'off', 'and', 'let', 'him', 'be'],
 ['you', 'think', 'he', 'll', 'let', 'us', 'be'],
 ['said', 'lark'],
 ['he', 'll', 'hunt', 'us', 'down'],
 ['you', 'want', 'to', 'be', 'hunted', 'you', 'great', 'muttonhead'],
 ['no', 'said', 'small', 'paul'],
 ['don', 'want', 'that'],
 ['don'],
 ['so', 'you', 'll', 'kill', 'him'],
 ['said', 'lark'],
 ['yes'],
 ['the',
  'huge',
  'man',
  'stamped',
  'the',
  'butt',
  'of',
  'his',
  'spear',
  'on',
  'the',
  'frozen',
  'riverbank'],
 ['will'],
 ['he', 'shouldn', 'hunt', 'us'],
 ['the',
  'sisterman',
  'took',
  'his',
  'hands',
  'from',
  'his',
  'armpits',
  'and',
  'turned',
  'to',
  'chett'],
 ['we', 'need', 'to', 'kill', 'all', 'the', 'officers', 'say'],
 ['chett', 'was', 'sick', 'of', 'hearing', 'it'],
 ['we', 'been', 'over', 'this'],
 ['the', 'old', 'bear', 'dies', 'and', 'blane', 'from', 'theshadowtower'],
 ['grubbs',
  'and',
  'aethan',
  'as',
  'well',
  'their',
  'ill',
  'luck',
  'for',
  'drawing',
  'the',
  'watch',
  'dywen',
  'and',
  'barmen',
  'for',
  'their',
  'tracking',
  'and',
  'ser',
  'piggy',
  'for',
  'the',
  'ravens'],
 ['that', 'all'],
 ['we', 'kill', 'them', 'quiet', 'while', 'they', 'sleep'],
 ['one', 'scream', 'and', 'we', 're', 'wormfood', 'every', 'one', 'of', 'us'],
 ['his', 'boils', 'were', 'red', 'with', 'rage'],
 ['just',
  'do',
  'your',
  'bit',
  'and',
  'see',
  'that',
  'your',
  'cousins',
  'do',
  'theirs'],
 ['and',
  'paul',
  'try',
  'and',
  'remember',
  'it',
  'third',
  'watch',
  'not',
  'second'],
 ['third',
  'watch',
  'the',
  'big',
  'man',
  'said',
  'through',
  'hair',
  'and',
  'frozen',
  'snot'],
 ['me', 'and', 'softfoot'],
 ['remember', 'chett'],
 ['the',
  'moon',
  'would',
  'be',
  'black',
  'tonight',
  'and',
  'they',
  'had',
  'jiggered',
  'the',
  'watches',
  'so',
  'as',
  'to',
  'have',
  'eight',
  'of',
  'their',
  'own',
  'standing',
  'sentry',
  'with',
  'two',
  'more',
  'guarding',
  'the',
  'horses'],
 ['it', 'wasn', 'going', 'to', 'get', 'much', 'riper', 'than', 'that'],
 ['besides',
  'page',
  'the',
  'wildlings',
  'could',
  'be',
  'upon',
  'them',
  'any',
  'day',
  'now'],
 ['chett',
  'meant',
  'to',
  'be',
  'well',
  'away',
  'from',
  'here',
  'before',
  'that',
  'happened'],
 ['he', 'meant', 'to', 'live'],
 ['three',
  'hundred',
  'sworn',
  'brothers',
  'of',
  'the',
  'night',
  'watch',
  'had',
  'ridden',
  'north',
  'two',
  'hundred',
  'from',
  'castle',
  'black',
  'and',
  'another',
  'hundred',
  'from',
  'theshadowtower'],
 ['it',
  'was',
  'the',
  'biggest',
  'ranging',
  'in',
  'living',
  'memory',
  'near',
  'third',
  'of',
  'the',
  'watch',
  'strength'],
 ['they',
  'meant',
  'to',
  'find',
  'ben',
  'stark',
  'ser',
  'waymar',
  'royce',
  'and',
  'the',
  'other',
  'rangers',
  'who',
  'gone',
  'missing',
  'and',
  'discover',
  'why',
  'the',
  'wildlings',
  'were',
  'leaving',
  'their',
  'villages'],
 ['well',
  'they',
  'were',
  'no',
  'closer',
  'to',
  'stark',
  'and',
  'royce',
  'than',
  'when',
  'they',
  'left',
  'the',
  'wall',
  'but',
  'they',
  'learned',
  'where',
  'all',
  'the',
  'wildlings',
  'had',
  'gone',
  'up',
  'into',
  'the',
  'icy',
  'heights',
  'of',
  'the',
  'godsforsaken',
  'frostfangs'],
 ['they',
  'could',
  'squat',
  'up',
  'there',
  'till',
  'the',
  'end',
  'of',
  'time',
  'and',
  'it',
  'wouldn',
  'prick',
  'chett',
  'boils',
  'none'],
 ['but', 'no'],
 ['they', 'were', 'coming', 'down'],
 ['down', 'the', 'milkwater'],
 ['chett', 'raised', 'his', 'eyes', 'and', 'there', 'it', 'was'],
 ['the',
  'river',
  'stony',
  'banks',
  'were',
  'bearded',
  'by',
  'ice',
  'its',
  'pale',
  'milky',
  'waters',
  'flowing',
  'endlessly',
  'down',
  'out',
  'of',
  'the',
  'frostfangs'],
 ['and',
  'now',
  'mance',
  'rayder',
  'and',
  'his',
  'wildlings',
  'were',
  'flowing',
  'down',
  'the',
  'same',
  'way'],
 ['thoren',
  'smallwood',
  'had',
  'returned',
  'in',
  'lather',
  'three',
  'days',
  'past'],
 ['while',
  'he',
  'was',
  'telling',
  'the',
  'old',
  'bear',
  'what',
  'his',
  'scouts',
  'had',
  'seen',
  'his',
  'man',
  'kedge',
  'whiteye',
  'told',
  'the',
  'rest',
  'of',
  'them'],
 ['they',
  're',
  'still',
  'well',
  'up',
  'the',
  'foothills',
  'but',
  'they',
  're',
  'coming',
  'kedge',
  'said',
  'warming',
  'his',
  'hands',
  'over',
  'the',
  'fire'],
 ['harma', 'the', 'dogshead', 'has', 'the', 'van', 'the', 'poxy', 'bitch'],
 ['goady',
  'crept',
  'up',
  'on',
  'her',
  'camp',
  'and',
  'saw',
  'her',
  'plain',
  'by',
  'the',
  'fire'],
 ['that',
  'fool',
  'tumberjon',
  'wanted',
  'to',
  'pick',
  'her',
  'off',
  'with',
  'an',
  'arrow',
  'but',
  'smallwood',
  'had',
  'better',
  'sense'],
 ['chett', 'spat'],
 ['how', 'many', 'were', 'there', 'could', 'you', 'tell'],
 ['many', 'and', 'more'],
 ['twenty', 'thirty', 'thousand', 'we', 'didn', 'stay', 'to', 'count'],
 ['harma',
  'had',
  'five',
  'hundred',
  'in',
  'the',
  'van',
  'every',
  'one',
  'ahorse'],
 ['the', 'men', 'around', 'the', 'fire', 'exchanged', 'uneasy', 'looks'],
 ['it',
  'was',
  'rare',
  'thing',
  'to',
  'find',
  'even',
  'dozen',
  'mounted',
  'wildlings',
  'and',
  'five',
  'hundred',
  'smallwood',
  'sent',
  'bannen',
  'and',
  'me',
  'wide',
  'around',
  'the',
  'van',
  'to',
  'catch',
  'peek',
  'at',
  'the',
  'main',
  'body',
  'kedge',
  'went',
  'on'],
 ['there', 'was', 'no', 'end', 'of', 'them'],
 ['they',
  're',
  'moving',
  'slow',
  'as',
  'frozen',
  'river',
  'four',
  'five',
  'miles',
  'day',
  'but',
  'they',
  'don',
  'look',
  'like',
  'they',
  'mean',
  'to',
  'go',
  'back',
  'to',
  'their',
  'villages',
  'neither'],
 ['more',
  'half',
  'were',
  'women',
  'and',
  'children',
  'and',
  'they',
  'were',
  'driving',
  'their',
  'animals',
  'before',
  'them',
  'goats',
  'sheep',
  'even',
  'aurochs',
  'dragging',
  'sledges'],
 ['they',
  'loaded',
  'up',
  'with',
  'bales',
  'of',
  'fur',
  'and',
  'sides',
  'of',
  'meat',
  'cages',
  'of',
  'chickens',
  'butter',
  'chums',
  'and',
  'spinning',
  'wheels',
  'every',
  'damn',
  'thing',
  'they',
  'own'],
 ['the',
  'mules',
  'and',
  'garrons',
  'was',
  'so',
  'heavy',
  'laden',
  'you',
  'think',
  'their',
  'backs',
  'would',
  'break'],
 ['the', 'women', 'as', 'well'],
 ['and', 'they', 'follow', 'the', 'milkwater'],
 ['lark', 'the', 'sisterman', 'asked'],
 ['said', 'so', 'didn'],
 ['the',
  'milkwater',
  'would',
  'take',
  'them',
  'past',
  'the',
  'fist',
  'of',
  'the',
  'first',
  'men',
  'the',
  'ancient',
  'ringfort',
  'where',
  'the',
  'night',
  'watch',
  'had',
  'made',
  'its',
  'camp'],
 ['any',
  'man',
  'with',
  'thimble',
  'of',
  'sense',
  'could',
  'see',
  'that',
  'it',
  'was',
  'time',
  'to',
  'pull',
  'up',
  'stakes',
  'and',
  'fall',
  'back',
  'on',
  'the',
  'wall'],
 ['the',
  'old',
  'bear',
  'had',
  'strengthened',
  'the',
  'fist',
  'with',
  'spikes',
  'and',
  'pits',
  'and',
  'caltrops',
  'but',
  'against',
  'such',
  'host',
  'all',
  'that',
  'was',
  'pointless'],
 ['if',
  'they',
  'stayed',
  'here',
  'they',
  'would',
  'be',
  'engulfed',
  'and',
  'overwhelmed'],
 ['and', 'thoren', 'smallwood', 'wanted', 'to', 'attack'],
 ['sweet',
  'donnel',
  'hill',
  'was',
  'squire',
  'to',
  'ser',
  'mallador',
  'locke',
  'and',
  'the',
  'night',
  'before',
  'last',
  'smallwood',
  'had',
  'come',
  'to',
  'locke',
  'tent'],
 ['ser',
  'mallador',
  'had',
  'been',
  'of',
  'the',
  'same',
  'mind',
  'as',
  'old',
  'ser',
  'ottyn',
  'wythers',
  'urging',
  'retreat',
  'on',
  'the',
  'wall',
  'but',
  'smallwood',
  'wanted',
  'to',
  'convince',
  'him',
  'otherwise'],
 ['page',
  'this',
  'king',
  'beyond',
  'the',
  'wall',
  'will',
  'never',
  'look',
  'for',
  'us',
  'so',
  'far',
  'north',
  'sweet',
  'donnel',
  'reported',
  'him',
  'saying'],
 ['and',
  'this',
  'great',
  'host',
  'of',
  'his',
  'is',
  'shambling',
  'horde',
  'full',
  'of',
  'useless',
  'mouths',
  'who',
  'won',
  'know',
  'what',
  'end',
  'of',
  'sword',
  'to',
  'hold'],
 ['one',
  'blow',
  'will',
  'take',
  'all',
  'the',
  'fight',
  'out',
  'of',
  'them',
  'and',
  'send',
  'them',
  'howling',
  'back',
  'to',
  'their',
  'hovels',
  'for',
  'another',
  'fifty',
  'years'],
 ['three', 'hundred', 'against', 'thirty', 'thousand'],
 ['chett',
  'called',
  'that',
  'rank',
  'madness',
  'and',
  'what',
  'was',
  'madder',
  'still',
  'was',
  'that',
  'ser',
  'mallador',
  'had',
  'been',
  'persuaded',
  'and',
  'the',
  'two',
  'of',
  'them',
  'together',
  'were',
  'on',
  'the',
  'point',
  'of',
  'persuading',
  'the',
  'old',
  'bear'],
 ['if',
  'we',
  'wait',
  'too',
  'ion',
  'this',
  'chance',
  'may',
  'be',
  'lost',
  'never',
  'to',
  'come',
  'again',
  'smallwood',
  'was',
  'saying',
  'to',
  'anyone',
  'who',
  'would',
  'listen'],
 ['against',
  'that',
  'ser',
  'ottyn',
  'wythers',
  'said',
  'we',
  'are',
  'the',
  'shield',
  'that',
  'guards',
  'the',
  'realms',
  'of',
  'men'],
 ['you',
  'do',
  'not',
  'throw',
  'away',
  'your',
  'shield',
  'for',
  'no',
  'good',
  'purpose',
  'but',
  'to',
  'that',
  'thoren',
  'smallwood',
  'said',
  'in',
  'swordfight',
  'man',
  'surest',
  'defense',
  'is',
  'the',
  'swift',
  'stroke',
  'that',
  'slays',
  'his',
  'foe',
  'not',
  'cringing',
  'behind',
  'shield'],
 ['neither', 'smallwood', 'nor', 'wythers', 'had', 'the', 'command', 'though'],
 ['lord',
  'mormont',
  'did',
  'and',
  'mormont',
  'was',
  'waiting',
  'for',
  'his',
  'other',
  'scouts',
  'for',
  'jarman',
  'buckwell',
  'and',
  'the',
  'men',
  'who',
  'climbed',
  'the',
  'giant',
  'stair',
  'and',
  'for',
  'qhorin',
  'halfhand',
  'and',
  'jon',
  'snow',
  'who',
  'gone',
  'to',
  'probe',
  'theskirlingpass',
  'buckwell',
  'and',
  'the',
  'halfhand',
  'were',
  'late',
  'in',
  'returning',
  'though'],
 ['dead', 'most', 'like'],
 ['chett',
  'pictured',
  'jon',
  'snow',
  'lying',
  'blue',
  'and',
  'frozen',
  'on',
  'some',
  'bleak',
  'mountaintop',
  'with',
  'wildling',
  'spear',
  'up',
  'his',
  'bastard',
  'arse'],
 ['the', 'thought', 'made', 'him', 'smile'],
 ['hope', 'they', 'killed', 'his', 'bloody', 'wolf', 'as', 'well'],
 ['there', 'no', 'bear', 'here', 'he', 'decided', 'abruptly'],
 ['just', 'an', 'old', 'print', 'that', 'all'],
 ['back', 'to', 'the', 'fist'],
 ['the',
  'dogs',
  'almost',
  'yanked',
  'him',
  'off',
  'his',
  'feet',
  'as',
  'eager',
  'to',
  'get',
  'back',
  'as',
  'he',
  'was'],
 ['maybe', 'they', 'thought', 'they', 'were', 'going', 'to', 'get', 'fed'],
 ['chett', 'had', 'to', 'laugh'],
 ['he',
  'hadn',
  'fed',
  'them',
  'for',
  'three',
  'days',
  'now',
  'to',
  'turn',
  'them',
  'mean',
  'and',
  'hungry'],
 ['tonight',
  'before',
  'slipping',
  'off',
  'into',
  'the',
  'dark',
  'he',
  'turn',
  'them',
  'loose',
  'among',
  'the',
  'horse',
  'lines',
  'after',
  'sweet',
  'donnel',
  'hill',
  'and',
  'clubfoot',
  'karl',
  'cut',
  'the',
  'tethers'],
 ['they',
  'll',
  'have',
  'snarling',
  'hounds',
  'and',
  'panicked',
  'horses',
  'all',
  'over',
  'the',
  'fist',
  'running',
  'through',
  'fires',
  'jumping',
  'the',
  'ringwall',
  'and',
  'trampling',
  'down',
  'tents'],
 ['with',
  'all',
  'the',
  'confusion',
  'it',
  'might',
  'be',
  'hours',
  'before',
  'anyone',
  'noticed',
  'that',
  'fourteen',
  'brothers',
  'were',
  'missing'],
 ['lark',
  'had',
  'wanted',
  'to',
  'bring',
  'in',
  'twice',
  'that',
  'number',
  'but',
  'what',
  'could',
  'you',
  'expect',
  'from',
  'some',
  'stupid',
  'fishbreath',
  'sisterman'],
 ['whisper',
  'word',
  'in',
  'the',
  'wrong',
  'ear',
  'and',
  'before',
  'you',
  'knew',
  'it',
  'you',
  'be',
  'short',
  'head'],
 ['no',
  'fourteen',
  'was',
  'good',
  'number',
  'enough',
  'to',
  'do',
  'what',
  'needed',
  'doing',
  'but',
  'not',
  'so',
  'many',
  'that',
  'they',
  'couldn',
  'keep',
  'the',
  'secret'],
 ['chett', 'had', 'recruited', 'most', 'of', 'them', 'himself'],
 ['small',
  'paul',
  'was',
  'one',
  'of',
  'his',
  'the',
  'strongest',
  'man',
  'on',
  'the',
  'wall',
  'even',
  'if',
  'he',
  'was',
  'slower',
  'than',
  'dead',
  'snail'],
 ['he', 'once', 'broken', 'wildling', 'back', 'with', 'hug'],
 ['they',
  'had',
  'dirk',
  'as',
  'well',
  'named',
  'for',
  'his',
  'favorite',
  'weapon',
  'and',
  'the',
  'little',
  'grey',
  'man',
  'the',
  'brothers',
  'called',
  'softfoot',
  'who',
  'raped',
  'hundred',
  'women',
  'in',
  'his',
  'youth',
  'and',
  'liked',
  'to',
  'boast',
  'how',
  'none',
  'had',
  'never',
  'seen',
  'nor',
  'heard',
  'him',
  'until',
  'he',
  'shoved',
  'it',
  'up',
  'inside',
  'them'],
 ['the', 'plan', 'was', 'chett'],
 ['he',
  'was',
  'the',
  'clever',
  'one',
  'he',
  'been',
  'steward',
  'to',
  'old',
  'maester',
  'aemon',
  'for',
  'four',
  'good',
  'years',
  'before',
  'that',
  'bastard',
  'jon',
  'snow',
  'had',
  'done',
  'him',
  'out',
  'so',
  'his',
  'job',
  'could',
  'be',
  'handed',
  'to',
  'his',
  'fat',
  'pig',
  'of',
  'friend'],
 ['when',
  'he',
  'killed',
  'sam',
  'tarly',
  'tonight',
  'he',
  'planned',
  'to',
  'whisper',
  'give',
  'my',
  'love',
  'to',
  'lord',
  'snow',
  'right',
  'in',
  'his',
  'ear',
  'before',
  'he',
  'sliced',
  'ser',
  'piggy',
  'throat',
  'open',
  'to',
  'let',
  'the',
  'blood',
  'come',
  'bubbling',
  'out',
  'through',
  'all',
  'those',
  'layers',
  'of',
  'suet'],
 ['chett',
  'knew',
  'the',
  'ravens',
  'so',
  'he',
  'wouldn',
  'have',
  'no',
  'trouble',
  'there',
  'no',
  'more',
  'than',
  'he',
  'would',
  'with',
  'tarly'],
 ['one',
  'touch',
  'of',
  'the',
  'knife',
  'and',
  'that',
  'craven',
  'would',
  'piss',
  'his',
  'pants',
  'and',
  'start',
  'blubbering',
  'for',
  'his',
  'life'],
 ['let', 'him', 'beg', 'it', 'won', 'do', 'him', 'no', 'good'],
 ['after',
  'he',

In [68]:
story[0]

['storm',
 'of',
 'swords',
 'book',
 'three',
 'of',
 'song',
 'of',
 'ice',
 'and',
 'fire',
 'by',
 'george']

In [86]:
import gensim
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [70]:
model.build_vocab(story)

In [71]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(1542339, 2049890)

In [72]:
model.wv.most_similar('daenerys')

[('mag', 0.9896919131278992),
 ('doom', 0.989369809627533),
 ('khal', 0.9884417057037354),
 ('eyed', 0.987953245639801),
 ('outlaw', 0.9877286553382874),
 ('tyroshi', 0.9870201349258423),
 ('raider', 0.9868928790092468),
 ('singer', 0.9868418574333191),
 ('numbers', 0.9866340160369873),
 ('collio', 0.986312210559845)]

In [73]:
model.wv.similarity('arya','sansa')

0.8560227

In [74]:
model.wv.get_normed_vectors().shape

(9475, 100)

In [75]:
y = model.wv.index_to_key

In [76]:
len(y)

9475

In [77]:
y

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'you',
 'was',
 'it',
 'in',
 'her',
 'that',
 'had',
 'she',
 'as',
 'but',
 'him',
 'with',
 'for',
 'not',
 'they',
 'said',
 'at',
 'on',
 'my',
 'have',
 'be',
 'is',
 'lord',
 'no',
 'them',
 'me',
 'all',
 'were',
 'from',
 'your',
 'would',
 'so',
 'when',
 'one',
 'ser',
 'if',
 'we',
 'could',
 'there',
 'will',
 'their',
 'are',
 'up',
 'did',
 'man',
 'king',
 'this',
 'or',
 'well',
 'back',
 'what',
 'more',
 'been',
 'by',
 'do',
 'down',
 'out',
 'jon',
 'who',
 'than',
 'page',
 'like',
 'only',
 'men',
 'now',
 'too',
 'father',
 'know',
 'before',
 'even',
 'never',
 'then',
 'old',
 'hand',
 'off',
 'tyrion',
 'see',
 'some',
 'made',
 'lady',
 'thought',
 'an',
 'll',
 'how',
 'into',
 'black',
 'jaime',
 'might',
 'told',
 'can',
 'time',
 'through',
 'long',
 'head',
 'come',
 'eyes',
 'still',
 'good',
 'sansa',
 'us',
 'once',
 'though',
 'arya',
 'red',
 'here',
 'took',
 'face',
 'where',
 'two',
 'say',
 'little',
 'over',
 'again',
 'has',
 'about',
 'way',
 'other',
 'boy',
 'three',
 'son',
 'saw',
 'came',
 'go',
 'brother',
 'wall',
 'night',
 'should',
 'am',
 'must',
 'away',
 'sword',
 'dead',
 'himself',
 'tell',
 'much',
 'look',
 'half',
 'sam',
 'own',
 'enough',
 'gave',
 'take',
 're',
 'want',
 'robb',
 'just',
 'looked',
 'turned',
 'make',
 'heard',
 'knew',
 'asked',
 'white',
 'after',
 'why',
 'think',
 'day',
 'snow',
 'first',
 'left',
 'castle',
 'blood',
 'around',
 'went',
 'every',
 'don',
 'great',
 'dany',
 'let',
 'woman',
 'any',
 'another',
 'fire',
 'mother',
 'catelyn',
 'our',
 'gold',
 'found',
 'horse',
 'its',
 'need',
 'behind',
 'done',
 'davos',
 'beneath',
 'keep',
 'girl',
 'against',
 'knight',
 'called',
 'bran',
 'queen',
 'many',
 'get',
 'hands',
 'feet',
 'grace',
 'joffrey',
 'hear',
 'maester',
 'yet',
 'find',
 'hair',
 'nothing',
 'ever',
 'seemed',
 'last',
 'across',
 'wine',
 'hard',
 'stood',
 'bloody',
 'give',
 'stark',
 'hundred',
 'those',
 'while',
 'same',
 'brothers',
 'put',
 'wanted',
 'better',
 'cersei',
 'cloak',
 'stone',
 'mouth',
 'cold',
 'water',
 'gods',
 'prince',
 'yes',
 'bear',
 'gone',
 'between',
 'big',
 'right',
 'stannis',
 'watch',
 'almost',
 'seen',
 'name',
 'place',
 'such',
 'grey',
 'sister',
 'small',
 'always',
 'dark',
 'very',
 'lost',
 'lannister',
 'killed',
 'won',
 'tywin',
 'until',
 'winterfell',
 'perhaps',
 'high',
 'shall',
 'most',
 'battle',
 'robert',
 'may',
 'voice',
 'something',
 'these',
 'few',
 'kill',
 'under',
 'wife',
 'true',
 've',
 'north',
 'going',
 'end',
 'mance',
 'others',
 'died',
 'brienne',
 'soon',
 'seven',
 'sent',
 'leave',
 'words',
 'river',
 'fingers',
 'felt',
 'years',
 'young',
 'die',
 'along',
 'strong',
 'beside',
 'does',
 'wind',
 'arm',
 'children',
 'door',
 'sound',
 'mean',
 'green',
 'hodor',
 'far',
 'past',
 'daughter',
 'iron',
 'brought',
 'hound',
 'tower',
 'light',
 'best',
 'walls',
 'got',
 'thing',
 'tried',
 'walder',
 'cut',
 'house',
 'both',
 'hot',
 'heart',
 'sweet',
 'sat',
 'side',
 'each',
 'hall',
 'free',
 'moment',
 'horses',
 'frey',
 'bastard',
 'tyrell',
 'nor',
 'child',
 'landing',
 'arms',
 'upon',
 'fear',
 'new',
 'herself',
 'wedding',
 'laughed',
 'above',
 'rock',
 'wildlings',
 'wolf',
 'toward',
 'trees',
 'city',
 'steel',
 'fight',
 'sons',
 'swords',
 'fell',
 'dragons',
 'thick',
 'burned',
 'pulled',
 'heavy',
 'clegane',
 'oh',
 'word',
 'war',
 'brown',
 'maybe',
 'riverrun',
 'remember',
 'bed',
 'thousand',
 'part',
 'rest',
 'remembered',
 'mormont',
 'days',
 'bolton',
 'which',
 'taken',
 'jorah',
 'close',
 'without',
 'uncle',
 'fool',
 'began',
 'rode',
 'ygritte',
 'open',
 'smile',
 'meant',
 'commander',
 'speak',
 'sleep',
 'air',
 'edmure',
 'wench',
 'life',
 'throat',
 'second',
 'pale',
 'wed',
 'coming',
 'ice',
 'dozen',
 'inside',
 'else',
 'bring',
 'feel',
 'help',
 'next',
 'love',
 'smiled',
 'set',
 'petyr',
 'four',
 'someone',
 'together',
 'moved',
 'gendry',
 'deep',
 'tongue',
 'brave',
 'huge',
 'full',
 'table',
 'legs',
 'certain',
 'gate',
 'steps',
 'rain',
 'squire',
 'lem',
 'honor',
 'call',
 'sea',
 'hope',
 'silver',
 'lysa',
 'please',
 'soft',
 'flames',
 'held',
 'neck',
 'ground',
 'given',
 'least',
 'caught',
 'sun',
 'hold',
 'beric',
 'wasn',
 'alone',
 'instead',
 'dragon',
 'women',
 'ran',
 'reached',
 'mine',
 'didn',
 'tall',
 'teeth',
 'rose',
 'pie',
 'knights',
 'ride',
 'skin',
 'shoulder',
 'world',
 'blue',
 'being',
 'morning',
 'meera',
 'turn',
 'sometimes',
 'wondered',
 'broken',
 'floor',
 'send',
 'song',
 'margaery',
 'people',
 'fat',
 'since',
 'lords',
 'nose',
 'matter',
 'things',
 'times',
 'harrenhal',
 'five',
 'death',
 'shouted',
 'foot',
 'tom',
 'jojen',
 'cannot',
 'grenn',
 'oberyn',
 'throne',
 'storm',
 'kept',
 'kingsguard',
 'stand',
 'ask',
 'suddenly',
 'used',
 'near',
 'wish',
 'doubt',
 'believe',
 'fist',
 'raised',
 'closed',
 'cup',
 'shield',
 'opened',
 'sky',
 'room',
 'leather',
 'spear',
 'truth',
 'aemon',
 'leg',
 'feast',
 'beyond',
 'gregor',
 'forward',
 'stupid',
 'watched',
 'none',
 'tree',
 'wore',
 'armor',
 'outside',
 'crown',
 'craster',
 'safe',
 'food',
 'beard',
 'wood',
 'walked',
 'aye',
 'warm',
 'wet',
 'top',
 'unsullied',
 'arrow',
 'melisandre',
 'six',
 'south',
 'eye',
 'sure',
 'husband',
 'blade',
 'wildling',
 'yellow',
 'shadow',
 'dwarf',
 'step',
 'golden',
 'answer',
 'thin',
 'eat',
 'below',
 'belly',
 'chest',
 'wolves',
 'lie',
 'aside',
 'later',
 'dogs',
 'run',
 'third',
 'bad',
 'arrows',
 'either',
 'spoke',
 'fighting',
 'drew',
 'thoros',
 'varys',
 'returned',
 'mountain',
 'remained',
 'ten',
 'summer',
 'liked',
 'lay',
 'short',
 'empty',
 'captain',
 'dagger',
 'sight',
 'command',
 'breath',
 'yours',
 'broke',
 'known',
 'waiting',
 'renly',
 'show',
 'kiss',
 'talk',
 'smell',
 'gilly',
 'hurt',
 'strength',
 'stop',
 'wrong',
 'loras',
 'trying',
 'chapter',
 'bit',
 'running',
 'sharp',
 'round',
 'lips',
 'finally',
 'fall',
 'try',
 'serve',
 'burning',
 'cloaks',
 'ned',
 'led',
 'reach',
 'spears',
 'longer',
 'onto',
 'served',
 'baratheon',
 'looking',
 'tormund',
 'bronn',
 'realized',
 'guards',
 'friend',
 'rayder',
 'west',
 'aerys',
 'maid',
 'trident',
 'tully',
 'casterly',
 'different',
 'pointed',
 'seem',
 'stopped',
 'kings',
 'eight',
 'master',
 'kissed',
 'reminded',
 'hill',
 'needed',
 'cleos',
 'giant',
 'pay',
 'stay',
 'septon',
 'commanded',
 'eunuch',
 'astapor',
 'dog',
 'home',
 'sail',
 'poor',
 'wooden',
 'year',
 'kevan',
 'gift',
 'fought',
 'camp',
 'moon',
 'shook',
 'belwas',
 'joff',
 'quick',
 'less',
 'singer',
 'darkness',
 'mad',
 'walk',
 'shoulders',
 'choice',
 'twisted',
 'friends',
 'knife',
 'ones',
 'blackwater',
 'covered',
 'return',
 'crow',
 'point',
 'within',
 'sandor',
 'kind',
 'shae',
 'wouldn',
 'fair',
 'screamed',
 'noye',
 'care',
 'raven',
 'chett',
 'flesh',
 'sooner',
 'cell',
 'boys',
 'sworn',
 'ears',
 'truly',
 'imp',
 'captive',
 'guard',
 'kingslayer',
 'standing',
 'work',
 'saddle',
 'direwolf',
 'bones',
 'grew',
 'offered',
 'falling',
 'closer',
 'horn',
 'heir',
 'pushed',
 'followed',
 'quiet',
 'touched',
 'merrett',
 'kingdoms',
 'forgotten',
 'leaves',
 'tears',
 'helm',
 'often',
 'drink',
 'saying',
 'low',
 'use',
 'silk',
 'satin',
 'yard',
 'born',
 'passed',
 'promised',
 'stepped',
 'bright',
 'couldn',
 'whole',
 'mind',
 'anything',
 'aegon',
 'magnar',
 'worse',
 'duty',
 'angry',
 'loved',
 'taste',
 'rhaegar',
 'fine',
 'lannisters',
 'mercy',
 'loose',
 'ship',
 'girls',
 'pink',
 'slave',
 'break',
 'wide',
 'whose',
 'highgarden',
 'ghost',
 'torch',
 'roof',
 'gates',
 'village',
 'fast',
 'myself',
 'dream',
 'climbed',
 'slynt',
 'save',
 'marry',
 'wait',
 'outlaws',
 'lifted',
 'east',
 'nine',
 'bronze',
 'pyp',
 'filled',
 'knees',
 'knows',
 'road',
 'fish',
 'twins',
 'threw',
 'late',
 'realm',
 'dragonstone',
 'aunt',
 'ought',
 'happened',
 'agreed',
 'making',
 'sort',
 'lion',
 'towers',
 'understand',
 'met',
 'atop',
 'themselves',
 'win',
 'bread',
 'started',
 'slowly',
 'course',
 'giants',
 'axe',
 'crows',
 'folk',
 'says',
 'pyke',
 'twice',
 'older',
 'wings',
 'jeyne',
 'besides',
 'anguy',
 'knee',
 'hide',
 'drunk',
 'westeros',
 'hung',
 'warned',
 'seat',
 'laugh',
 'bird',
 'pain',
 'dome',
 'marriage',
 'axell',
 'swear',
 'named',
 'harwin',
 'boat',
 'chain',
 'slow',
 'sorry',
 'beautiful',
 'easy',
 'coin',
 'meat',
 'whatever',
 'goat',
 'boots',
 'mounted',
 'paul',
 'frozen',
 'smoke',
 'fallen',
 'dothraki',
 'tourney',
 'sing',
 'pray',
 'live',
 'protect',
 'beat',
 'needs',
 'arstan',
 'heads',
 'pull',
 'tent',
 'dying',
 'shouting',
 'finger',
 'mail',
 'glanced',
 'halfhand',
 'faces',
 'arryn',
 'learned',
 'waited',
 'pass',
 'common',
 'riding',
 'yourself',
 'daughters',
 'neither',
 'because',
 'ear',
 'mud',
 'whitebeard',
 'dawn',
 'answered',
 'balon',
 'flew',
 'move',
 'tarly',
 'edge',
 'lad',
 'dreams',
 'wants',
 'ships',
 'insisted',
 'bow',
 'doing',
 'question',
 'front',
 'silence',
 'thank',
 'kraznys',
 'alive',
 'climb',
 'cousin',
 'lothar',
 'woke',
 'blind',
 'surely',
 'taking',
 'narrow',
 'ago',
 'dressed',
 'sounded',
 'slaves',
 'wound',
 'slid',
 'hoster',
 'scarcely',
 'mace',
 'ugly',
 'pleased',
 'makes',
 'younger',
 'stones',
 'freys',
 'fit',
 'among',
 'till',
 'clothes',
 'seems',
 'janos',
 'smallwood',
 'greyjoy',
 'apart',
 'whispered',
 'wonder',
 'weak',
 'drank',
 'wise',
 'grown',
 'lived',
 'moving',
 'lightning',
 'thinking',
 'ale',
 'telling',
 'crossed',
 'blew',
 'sang',
 'salt',
 'already',
 'anyone',
 'helped',
 'tired',
 'jarl',
 'littlefinger',
 'frightened',
 'play',
 'ahead',
 'flowers',
 'yunkai',
 'slain',
 'names',
 'during',
 'follow',
 'amongst',
 'unless',
 'dance',
 'dry',
 'banners',
 'softly',
 'meereen',
 'swore',
 'sit',
 'catch',
 'stump',
 'pretty',
 'doesn',
 'quite',
 'tight',
 'land',
 'growing',
 ...]

In [78]:
from sklearn.decomposition import PCA

In [79]:
pca = PCA(n_components=3)

In [80]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [81]:
X

array([[ 0.41378292, -0.16867474, -0.44191316],
       [ 0.46382937, -0.07308131, -0.22985356],
       [-0.4444824 , -0.32003194,  0.11361028],
       ...,
       [ 0.01541914, -0.01803893,  0.07027628],
       [-0.09305401, -0.15789518, -0.10172106],
       [ 0.29700777,  0.06305301,  0.06839247]], dtype=float32)

In [82]:
X.shape

(9475, 3)

In [85]:
import plotly.express as px
fig = px.scatter_3d(X[200:300],x=0,y=1,z=2, color=y[200:300])
fig.show()