In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
from nltk.corpus import stopwords
import string
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import confusion_matrix
pd.set_option('display.max_colwidth', 255)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [4]:
df=pd.read_csv(r"C:\Users\chait\OneDrive\Documents\Generative-Ai\Generative-AI\Gen-AI\IMDB Dataset.csv")
df.head()

,review,sentiment
0,"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of v...",positive
1,"A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen-...",positive
2,"I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well b...",positive
3,"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br...",negative
4,"Petter Mattei's ""Love in the Time of Money"" is a visually stunning film to watch. Mr. Mattei offers us a vivid portrait about human relations. This is a movie that seems to be telling us what money, power and success do to people in the different situ...",positive

In [5]:
df.shape

(50000, 2)

In [6]:
df=df.iloc[:1000]
df.head()

,review,sentiment
0,"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of v...",positive
1,"A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen-...",positive
2,"I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well b...",positive
3,"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br...",negative
4,"Petter Mattei's ""Love in the Time of Money"" is a visually stunning film to watch. Mr. Mattei offers us a vivid portrait about human relations. This is a movie that seems to be telling us what money, power and success do to people in the different situ...",positive

In [7]:
df.shape

(1000, 2)

In [8]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [9]:
df['sentiment'].value_counts()

sentiment
positive    501
negative    499
Name: count, dtype: int64

In [10]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [11]:
df.duplicated().sum()

0

In [12]:
import re
def remove_html_tags(text):
    clean=re.compile('<.*?>')
    return re.sub(clean,'',text)

In [16]:
df['review']=df['review'].apply(remove_html_tags)
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [17]:
df['review'] = df['review'].apply(lambda x: x.lower())

In [18]:
#stopwords removal
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\chait\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [19]:
def remove_stopwords(text):
    newtext=[]
    for word in text.split():
        if word in stopwords.words('english'):
            newtext.append('')
        else:
            newtext.append(word)
    x=newtext[:]
    newtext.clear()
    return " ".join(x)

In [20]:
df['review']=df['review'].apply(remove_stopwords)

In [22]:
df['review'][10]

'phil  alien  one   quirky films   humour  based around  oddness  everything rather  actual punchlines.at first    odd  pretty funny    movie progressed   find  jokes  oddness funny anymore.its  low budget film (thats never  problem  itself),    pretty interesting characters,  eventually   lost interest.i imagine  film would appeal   stoner   currently partaking.for something similar  better try "brother  another planet"'

In [33]:
X=df.iloc[:,0:1]
y=df['sentiment']

In [34]:
X.head()

                                                                                                                                                                                                                                                           review
0  one    reviewers  mentioned   watching  1 oz episode   hooked.   right,    exactly  happened  me.the first thing  struck   oz   brutality  unflinching scenes  violence,  set  right   word go. trust me,     show   faint hearted  timid.  show pulls  pun...
1   wonderful little production.  filming technique   unassuming-  old-time-bbc fashion  gives  comforting,  sometimes discomforting, sense  realism   entire piece.  actors  extremely well chosen- michael sheen   "has got   polari"      voices  pat too! ...
2   thought    wonderful way  spend time    hot summer weekend, sitting   air conditioned theater  watching  light-hearted comedy.  plot  simplistic,   dialogue  witty   characters  likable (even  well bread suspected serial killer).   may  disappointed ...
3  basically there's  family   little boy (jake) thinks there's  zombie   closet &  parents  fighting   time.this movie  slower   soap opera...  suddenly, jake decides  become rambo  kill  zombie.ok, first     going  make  film  must decide    thriller  ...
4  petter mattei's "love   time  money"   visually stunning film  watch. mr. mattei offers us  vivid portrait  human relations.    movie  seems   telling us  money, power  success   people   different situations  encounter.    variation   arthur schnitzl...

In [35]:
y

0      positive
1      positive
2      positive
3      negative
4      positive
5      positive
6      positive
7      negative
8      negative
9      positive
10     negative
11     negative
12     negative
13     negative
14     positive
15     negative
16     positive
17     negative
18     positive
19     negative
20     positive
21     negative
22     positive
23     negative
24     negative
25     positive
26     positive
27     negative
28     negative
29     positive
30     positive
31     positive
32     negative
33     positive
34     negative
35     negative
36     negative
37     negative
38     positive
39     negative
40     negative
41     positive
42     negative
43     negative
44     positive
45     positive
46     negative
47     negative
48     positive
49     negative
50     positive
51     positive
52     positive
53     positive
54     negative
55     negative
56     negative
57     negative
58     positive
59     positive
60     negative
61     negative
62     positive
63     negative
64     negative
65     positive
66     negative
67     negative
68     negative
69     negative
70     negative
71     negative
72     positive
73     positive
74     negative
75     positive
76     positive
77     negative
78     negative
79     positive
80     positive
81     negative
82     negative
83     negative
84     negative
85     negative
86     negative
87     negative
88     negative
89     negative
90     positive
91     negative
92     positive
93     positive
94     negative
95     positive
96     negative
97     negative
98     negative
99     positive
100    positive
101    negative
102    positive
103    positive
104    negative
105    positive
106    positive
107    negative
108    positive
109    positive
110    negative
111    negative
112    negative
113    positive
114    positive
115    positive
116    positive
117    negative
118    negative
119    negative
120    positive
121    positive
122    negative
123    negative
124    positive
125    negative
126    negative
127    negative
128    positive
129    positive
130    positive
131    positive
132    negative
133    negative
134    negative
135    negative
136    positive
137    negative
138    positive
139    negative
140    negative
141    negative
142    negative
143    positive
144    negative
145    positive
146    positive
147    positive
148    negative
149    negative
150    positive
151    negative
152    negative
153    positive
154    negative
155    negative
156    negative
157    positive
158    negative
159    positive
160    positive
161    negative
162    negative
163    negative
164    positive
165    negative
166    positive
167    negative
168    negative
169    negative
170    negative
171    negative
172    positive
173    positive
174    negative
175    negative
176    positive
177    negative
178    positive
179    negative
180    positive
181    negative
182    negative
183    negative
184    negative
185    negative
186    positive
187    negative
188    positive
189    negative
190    positive
191    positive
192    positive
193    positive
194    negative
195    negative
196    negative
197    negative
198    positive
199    negative
200    negative
201    positive
202    positive
203    positive
204    negative
205    positive
206    negative
207    negative
208    positive
209    positive
210    negative
211    negative
212    negative
213    positive
214    negative
215    positive
216    positive
217    negative
218    positive
219    negative
220    negative
221    positive
222    positive
223    negative
224    positive
225    negative
226    positive
227    positive
228    positive
229    positive
230    negative
231    positive
232    positive
233    positive
234    positive
235    positive
236    positive
237    negative
238    positive
239    negative
240    negative
241    positive
242    negative
243    positive
244    negative
245    positive
246    negative
247    negative
248    positive
249    negative
250    negative
251    negative
252    negative
253    negative
254    positive
255    negative
256    negative
257    negative
258    positive
259    positive
260    positive
261    negative
262    negative
263    negative
264    negative
265    positive
266    negative
267    negative
268    negative
269    positive
270    negative
271    positive
272    positive
273    positive
274    negative
275    positive
276    negative
277    positive
278    negative
279    positive
280    positive
281    negative
282    negative
283    negative
284    positive
285    negative
286    positive
287    positive
288    positive
289    positive
290    positive
291    positive
292    positive
293    positive
294    positive
295    negative
296    negative
297    positive
298    positive
299    positive
300    negative
301    negative
302    positive
303    positive
304    positive
305    positive
306    positive
307    negative
308    negative
309    negative
310    positive
311    negative
312    negative
313    negative
314    negative
315    negative
316    positive
317    positive
318    positive
319    negative
320    positive
321    positive
322    negative
323    positive
324    negative
325    positive
326    positive
327    negative
328    positive
329    positive
330    negative
331    positive
332    positive
333    positive
334    positive
335    negative
336    positive
337    positive
338    negative
339    negative
340    negative
341    positive
342    negative
343    positive
344    negative
345    negative
346    negative
347    positive
348    negative
349    negative
350    positive
351    negative
352    negative
353    positive
354    negative
355    negative
356    positive
357    negative
358    negative
359    negative
360    positive
361    negative
362    positive
363    positive
364    positive
365    negative
366    negative
367    negative
368    positive
369    positive
370    positive
371    positive
372    negative
373    positive
374    positive
375    negative
376    positive
377    negative
378    positive
379    negative
380    negative
381    positive
382    positive
383    negative
384    negative
385    negative
386    negative
387    positive
388    positive
389    positive
390    positive
391    negative
392    positive
393    positive
394    positive
395    negative
396    negative
397    positive
398    negative
399    positive
400    positive
401    negative
402    negative
403    positive
404    positive
405    negative
406    positive
407    positive
408    negative
409    positive
410    negative
411    positive
412    negative
413    negative
414    negative
415    negative
416    negative
417    positive
418    negative
419    negative
420    negative
421    negative
422    negative
423    positive
424    negative
425    positive
426    positive
427    positive
428    negative
429    positive
430    negative
431    negative
432    negative
433    positive
434    negative
435    positive
436    positive
437    positive
438    positive
439    positive
440    negative
441    positive
442    negative
443    negative
444    negative
445    negative
446    negative
447    positive
448    negative
449    negative
450    positive
451    positive
452    negative
453    positive
454    positive
455    positive
456    negative
457    positive
458    negative
459    negative
460    positive
461    positive
462    negative
463    negative
464    negative
465    positive
466    positive
467    positive
468    negative
469    positive
470    negative
471    negative
472    negative
473    negative
474    positive
475    positive
476    positive
477    negative
478    negative
479    positive
480    negative
481    positive
482    negative
483    positive
484    positive
485    negative
486    negative
487    positive
488    positive
489    negative
490    negative
491    positive
492    positive
493    positive
494    positive
495    negative
496    negative
497    negative
498    negative
499    positive
500    negative
501    positive
502    positive
503    negative
504    positive
505    positive
506    negative
507    positive
508    negative
509    positive
510    negative
511    negative
512    negative
513    negative
514    negative
515    positive
516    negative
517    positive
518    positive
519    negative
520    negative
521    positive
522    positive
523    negative
524    negative
525    negative
526    positive
527    negative
528    positive
529    negative
530    negative
531    positive
532    positive
533    positive
534    positive
535    negative
536    negative
537    negative
538    negative
539    positive
540    positive
541    negative
542    negative
543    negative
544    negative
545    negative
546    negative
547    positive
548    negative
549    positive
550    negative
551    negative
552    positive
553    negative
554    negative
555    negative
556    positive
557    positive
558    positive
559    negative
560    negative
561    negative
562    negative
563    negative
564    positive
565    negative
566    positive
567    positive
568    positive
569    negative
570    positive
571    positive
572    positive
573    negative
574    negative
575    negative
576    negative
577    negative
578    negative
579    positive
580    positive
581    negative
582    positive
583    negative
584    positive
585    positive
586    positive
587    negative
588    negative
589    negative
590    positive
591    negative
592    positive
593    positive
594    positive
595    positive
596    negative
597    positive
598    positive
599    negative
600    positive
601    positive
602    positive
603    negative
604    negative
605    positive
606    positive
607    positive
608    positive
609    positive
610    negative
611    positive
612    negative
613    negative
614    positive
615    negative
616    positive
617    negative
618    positive
619    negative
620    positive
621    positive
622    positive
623    negative
624    positive
625    negative
626    positive
627    negative
628    positive
629    positive
630    negative
631    positive
632    positive
633    positive
634    positive
635    negative
636    negative
637    negative
638    positive
639    positive
640    negative
641    positive
642    negative
643    positive
644    negative
645    positive
646    negative
647    positive
648    positive
649    negative
650    positive
651    negative
652    negative
653    positive
654    negative
655    negative
656    positive
657    positive
658    positive
659    negative
660    negative
661    positive
662    positive
663    positive
664    positive
665    negative
666    positive
667    positive
668    negative
669    positive
670    positive
671    negative
672    negative
673    negative
674    negative
675    negative
676    positive
677    positive
678    negative
679    negative
680    positive
681    negative
682    positive
683    positive
684    negative
685    negative
686    positive
687    negative
688    negative
689    positive
690    positive
691    negative
692    negative
693    positive
694    positive
695    negative
696    positive
697    positive
698    positive
699    negative
700    negative
701    positive
702    negative
703    positive
704    positive
705    negative
706    positive
707    positive
708    negative
709    negative
710    positive
711    positive
712    positive
713    positive
714    positive
715    negative
716    negative
717    negative
718    negative
719    negative
720    negative
721    negative
722    positive
723    positive
724    positive
725    negative
726    positive
727    positive
728    positive
729    negative
730    positive
731    negative
732    positive
733    positive
734    positive
735    positive
736    negative
737    positive
738    negative
739    positive
740    negative
741    positive
742    negative
743    positive
744    negative
745    positive
746    positive
747    positive
748    negative
749    positive
750    positive
751    negative
752    negative
753    negative
754    negative
755    positive
756    negative
757    negative
758    negative
759    positive
760    positive
761    negative
762    positive
763    negative
764    positive
765    negative
766    negative
767    negative
768    negative
769    negative
770    negative
771    negative
772    positive
773    positive
774    negative
775    positive
776    negative
777    negative
778    positive
779    negative
780    positive
781    positive
782    positive
783    negative
784    negative
785    negative
786    positive
787    positive
788    negative
789    positive
790    positive
791    negative
792    positive
793    positive
794    negative
795    positive
796    positive
797    positive
798    negative
799    positive
800    positive
801    positive
802    positive
803    positive
804    positive
805    negative
806    positive
807    positive
808    positive
809    negative
810    negative
811    positive
812    positive
813    positive
814    positive
815    negative
816    positive
817    positive
818    positive
819    negative
820    positive
821    positive
822    positive
823    positive
824    negative
825    positive
826    positive
827    negative
828    negative
829    negative
830    negative
831    positive
832    positive
833    negative
834    negative
835    positive
836    negative
837    positive
838    positive
839    positive
840    positive
841    negative
842    positive
843    negative
844    positive
845    negative
846    positive
847    negative
848    negative
849    positive
850    positive
851    negative
852    positive
853    positive
854    negative
855    positive
856    positive
857    negative
858    positive
859    negative
860    positive
861    negative
862    negative
863    positive
864    positive
865    negative
866    positive
867    positive
868    negative
869    positive
870    negative
871    positive
872    positive
873    positive
874    positive
875    negative
876    positive
877    negative
878    negative
879    negative
880    negative
881    negative
882    negative
883    negative
884    positive
885    negative
886    negative
887    positive
888    positive
889    positive
890    positive
891    positive
892    positive
893    negative
894    positive
895    positive
896    positive
897    positive
898    negative
899    negative
900    positive
901    negative
902    negative
903    negative
904    negative
905    negative
906    positive
907    positive
908    positive
909    positive
910    positive
911    positive
912    negative
913    negative
914    negative
915    positive
916    negative
917    positive
918    positive
919    positive
920    positive
921    negative
922    negative
923    positive
924    negative
925    positive
926    negative
927    negative
928    positive
929    positive
930    positive
931    positive
932    negative
933    negative
934    negative
935    positive
936    negative
937    negative
938    negative
939    positive
940    negative
941    positive
942    negative
943    positive
944    positive
945    negative
946    positive
947    positive
948    positive
949    positive
950    positive
951    positive
952    positive
953    positive
954    positive
955    positive
956    negative
957    positive
958    negative
959    negative
960    positive
961    positive
962    positive
963    positive
964    positive
965    negative
966    negative
967    positive
968    positive
969    negative
970    negative
971    negative
972    positive
973    negative
974    negative
975    negative
976    negative
977    negative
978    negative
979    positive
980    negative
981    negative
982    negative
983    negative
984    positive
985    positive
986    positive
987    positive
988    positive
989    negative
990    negative
991    negative
992    positive
993    negative
994    positive
995    positive
996    negative
997    negative
998    negative
999    negative
Name: sentiment, dtype: object

In [36]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y=encoder.fit_transform(y)

In [38]:
y

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0])

In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [41]:
X_train.shape

(800, 1)

In [44]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [48]:
X_train_bow=cv.fit_transform(X_train['review']).toarray()
X_test_bow=cv.transform(X_test['review']).toarray()

In [49]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [50]:
X_test_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [53]:
from sklearn.naive_bayes import GaussianNB
gb=GaussianNB()

gb.fit(X_train_bow,y_train)

GaussianNB()

In [55]:
y_pred=gb.predict(X_test_bow)
from sklearn.metrics import accuracy_score,confusion_matrix

In [56]:
accuracy_score(y_test,y_pred)

0.555

In [57]:
confusion_matrix(y_test,y_pred)

array([[58, 56],
       [33, 53]], dtype=int64)

In [59]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_train_bow,y_train)
y_pred=rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8

In [62]:
cv=CountVectorizer(max_features=300)
X_train_bow=cv.fit_transform(X_train['review']).toarray()
X_test_bow=cv.transform(X_test['review']).toarray()

rf.fit(X_train_bow,y_train)
y_pred=rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.79

In [66]:
import gensim
model =gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [67]:
model.build_vocab(df)

In [68]:
model.train(df,total_examples=len(df),epochs=10)

(7, 150)

In [77]:
df['tokenized_reviews'] = df['review'].apply(lambda x: x.lower().split())

In [79]:
sentences=df['tokenized_reviews'].tolist()

In [80]:
model=gensim.models.Word2Vec(sentences,vector_size=100,window=5,min_count=2,workers=10,epochs=10)

In [81]:
import numpy as np
def document_vector(model, doc):
    words = [word for word in doc if word in model.wv]
    if len(words) == 0:
        return np.zeros(model.vector_size)
    return np.mean(model.wv[words], axis=0)

df['doc_vector'] = df['tokenized_reviews'].apply(lambda x: document_vector(model, x))

In [82]:
X = np.vstack(df['doc_vector'].values)  # convert list of vectors to 2D array
y = df['sentiment'].values

In [83]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [84]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [87]:
acc=rf.score(X_test,y_test)
acc

0.595

In [88]:
from transformers import pipeline

None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

In [89]:
classifier=pipeline("sentiment-analysis")
result=classifier("Spider man  movie was okay but i think they could have done more better still its one of the best")
print(result)

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

c:\Users\chait\miniconda3\envs\nlp-env\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\chait\.cache\huggingface\hub\models--distilbert--distilbert-base-uncased-finetuned-sst-2-english. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

NameError: name 'torch' is not defined

In [2]:
!nvidia-smi

Sat Aug 23 12:15:50 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.88                 Driver Version: 580.88         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   56C    P8              3W /   90W |     212MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A           24292    C+G   ...Browser\Application\brave.exe      N/A      |
|    0   N/A  N/A           24532    C+G   ...Browser\Application\brave.exe      N/A      |
+-----------------------------------------------------------------------------------------+